# Project options - can change the overall project title
# and the name of the output directory here
# Uncomment the post-render command to use the 
# return-to-source post script - see Readme
project:
  title: "Slides"
  output-dir: "_output"
  # post-render: scripts/return-to-source.ts

# options for all formats - suggested not to change
from: markdown+raw_attribute+raw_tex
filters: 
  - scripts/shortcodes.lua
standalone: true
self-contained: true
slide-level: 2

# set a module code to show up on all HTML and PDF outputs - can be
# any string, e.g. 'ST4011', or 'Spring Term'
modulecode: ''

# biobliography options - if using other file names
# or multiple bibliography files, change/add them here
# Can also change the referencing style here using a
# different csl file - many more can be found at
# https://github.com/citation-style-language/styles
bibliography:
  - bibliography/references.bib
csl: bibliography/citethemright10th.csl

# output format options - change these as required
format:
  beamer:
    pdf-engine: xelatex
    include-in-header: templates/beamerheader.tex
    include-before-body: templates/beamerprefix.tex
    include-after-body: templates/beamersuffix.tex
    fontsize: 12pt # 10, 11, or 12pt
  html:
    template: templates/html.html
    toc: false # turn table of contents on/off
  pptx:
    reference-doc: templates/pptx/cosmic-latte.pptx
  revealjs:
    theme: templates/slide-theme.scss
    transition: slide
    margin: 0.2
    smaller: false
    subtitle: ''
    output-ext: htm
